[tool.black]
line-length = 88
target-version = ['py39']

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "W", "C90", "D", "PL", "N", "RUF"]
ignore = ["D203", "D213"]
exclude = ["tests/"]

[tool.mypy]
strict = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_defs = true